[server]
address = "0.0.0.0"
port = 5666

[database.default]
link = "pgsql:gva:gva@tcp(127.0.0.1:5433)/gva?sslmode=disable"
type = "pgsql"
debug = false

[casbin]
model = "resource/casbin/model.conf"

[auth]
jwt_secret = "bdfeac500e20fdc56695c3550ddd52ceb2499d6700bf93a34f5493febbbdd278"
refresh_secret = "88c79a961ab6705815bad8618c2012ff571f5267623b94d631c660a4a0e8d85f"

[upload]
storage = "local"
max_size_mb = 10
local_dir = "resource/uploads"

[upload.s3]
endpoint = ""
region = ""
bucket = ""
access_key = ""
secret_key = ""
use_ssl = true
prefix = "uploads"
