[server]
address = "0.0.0.0"
port = 5666

[database.default]
link = "pgsql:gva:gva@tcp(127.0.0.1:5432)/gva?sslmode=disable"
type = "pgsql"
debug = true

[casbin]
model = "resource/casbin/model.conf"

[auth]
jwt_secret = ""
refresh_secret = ""

[upload]
storage = "local"
max_size_mb = 10
local_dir = "resource/uploads"

[upload.s3]
endpoint = ""
region = ""
bucket = ""
access_key = ""
secret_key = ""
use_ssl = true
prefix = "uploads"
